apiVersion: v1
data:
  A: Bx0fl3R3agbiJMCPkU5r48HC1ZgDohW3OHsc4ObECDU0Q1pI3lcF9UDKwoFY58wo.lSQkTaKZYyWUodQE.zyFP4PwXUed2lJgU3pmygQ==
kind: Secret
metadata:
  name: guestbook-secret
# kubesec:v:3
# kubesec:gcp:projects/geralvin-infra/locations/asia-southeast1/keyRings/geralvin/cryptoKeys/main:CiQAO0zzb4ug5bB0qiGUDU/xZOj1FAUAqS77yO7pVLt/KIn9DzMSSQCHnZZg/ddDvnnQmRRwQ7KDQhRORaZa2n1p4Dov4HG9MIvOmEcrRtjxKskDWcQZPVX3cIVjUJ5cJ+6kYHQ/4Q3xm/CS1TnkkpU=
# kubesec:mac:lnyMA1rdxiScxheR.qeNCwGrIIVNf5esd9oSULw==

