apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.name }}
  labels:
    app: {{ .Values.config.name }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Values.config.name }}
    heritage: {{ .Release.Service }}
    version: x
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.config.name }}
      release: {{ .Values.config.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.name }}
        release: {{ .Values.config.name }}
    spec:
      containers:
        - name: {{ .Values.config.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: helm-guestbook-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
