apiVersion: v1
data:
  A: kaZbNFvpY3HX3VovSq+SZoppeXCB1J7mxVnsIdAoRi19opAEsFu0e8sFzCRCHZDf.XkXxqpc3ML/R/V9h.Lh331Xd32Wi7+hhr+Pfjew==
  B: JuD6RKeJJOBEUmjLdJZUjc5LDsSe46dRyT1Xeui/FpbjO+nTq5pdRVfMh1Q2cy2U.L4V39Mmcj6gC7fzX.ElWCle9ldZJfL/1Uzg2alw==
  DB_PASSWORD: c6w6FjRvFicTINjEITv61gyrj9xZfUOrk5bu3NWRwD8wiCQG6nOCFBBNSOPbsWLj.8AHc6aWm4gu8nsVB.0rO9aonwjrLdyhIHZPGMeA==
  DB_USERNAME: X5X7vW6KX6bZbidzFrqXda3WIyUuUkN5qePAmsK6xcD8kfdE+E/cZO0gREpj19BO.V+ByvO7qGongqayk.b6fLDnBpzzBLUgi6ESseTQ==
  INDONESIA: MVeEctXxGssHfuux9Q0QjDS48IM+hJtinoCA+4cuSObDw9VbYOrLBePWo+6wn5JP.wYB0zV1G46fm0sEF.KiqaPj0k84Ssm9Uvw/yYvA==
  MONYET: iqBHgRKcUt1mg9oXbAker1kpekQ2+T8a3I/1jtDs+e3tz2EW/cO5N5BmTJLAZCE4.oSh+vYxdWDVEP5sG.mUBxnbGsPU78l9StRp9G7g==
kind: Secret
metadata:
  name: helm-guestbook-secret
# kubesec:v:3
# kubesec:gcp:projects/geralvin-infra/locations/asia-southeast1/keyRings/geralvin/cryptoKeys/main:CiQAO0zzb69kxTzY3r4rzFjsbdONAxdYYuBmUPZ9vo9M/Tu2fH0SSQCHnZZgutmbohmhfo1PlzQetxp2Oa6HiPGmP+lHSP3nBmTa0TKBQegByszx46HswtWOnl+GtDuUstOymmRRJCsBOxW1r62Iil0=
# kubesec:mac:hj84W6Q+lf86xK6m.nXAlIasQU4l+4Q965IK58g==